In [10]:
import os
import pandas as pd
from DataPreProcessing import PreProcessing

In [11]:
path=os.getcwd()

In [12]:
path

'G:\\Projects\\Machine Learning\\WaferSensorFaultDetection\\notebooks'

In [13]:
os.chdir("G:\\Projects\\Machinelearning\\WaferSensorFaultDetection")

SyntaxError: invalid syntax (3263651684.py, line 1)

In [27]:
preprocess=PreProcessing.PreProcessing()

In [34]:
df = pd.read_sql_query("select * from wafer", session)

In [35]:
df.head()

,index,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-6,Sensor-7,Sensor-8,Sensor-9,...,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590,Good/Bad
0,0,3076.81,2158.75,2208.2334,1517.0152,1.0980,100.0,110.1900,0.1247,1.4357,...,64.2405,0.5016,0.0152,0.0040,3.0319,0.0465,0.0299,0.0090,64.2405,-1
1,1,2951.62,2511.92,2253.5111,1397.5060,0.9660,100.0,109.7611,0.1210,1.5527,...,0.0000,0.4953,0.0105,0.0037,2.1266,-0.0012,0.0252,0.0081,0.0000,-1
2,2,2930.42,2505.17,2235.0556,1302.6607,1.6347,100.0,109.9856,0.1230,1.4588,...,NaN,0.4958,0.0111,0.0033,2.2296,-0.0012,0.0252,0.0081,0.0000,-1
3,3,2997.28,2357.99,2141.0667,1236.5212,0.9698,100.0,98.3344,0.1238,1.5973,...,NaN,0.4962,0.0086,0.0024,1.7297,-0.0012,0.0252,0.0081,0.0000,-1
4,4,3025.10,2475.18,2235.0556,1302.6607,1.6347,100.0,109.9856,0.1230,1.5525,...,NaN,0.4983,0.0159,0.0041,3.1927,-0.0012,0.0252,0.0081,0.0000,-1

In [36]:
df1=preprocess.KNNImputer(df)

In [37]:
features = df1.drop(['Good/Bad','index'], axis=1)
labels = df1['Good/Bad']

In [38]:
features

,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-6,Sensor-7,Sensor-8,Sensor-9,Sensor-10,...,Sensor-581,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590
0,3076.81,2158.75,2208.2334,1517.0152,1.0980,100.0,110.1900,0.1247,1.4357,0.0089,...,0.00900,64.24050,0.50160,0.01520,0.00400,3.03190,0.0465,0.0299,0.0090,64.2405
1,2951.62,2511.92,2253.5111,1397.5060,0.9660,100.0,109.7611,0.1210,1.5527,0.0119,...,0.00810,0.00000,0.49530,0.01050,0.00370,2.12660,-0.0012,0.0252,0.0081,0.0000
2,2930.42,2505.17,2235.0556,1302.6607,1.6347,100.0,109.9856,0.1230,1.4588,-0.0143,...,0.00680,73.02178,0.49580,0.01110,0.00330,2.22960,-0.0012,0.0252,0.0081,0.0000
3,2997.28,2357.99,2141.0667,1236.5212,0.9698,100.0,98.3344,0.1238,1.5973,-0.0534,...,0.00412,90.40428,0.49620,0.00860,0.00240,1.72970,-0.0012,0.0252,0.0081,0.0000
4,3025.10,2475.18,2235.0556,1302.6607,1.6347,100.0,109.9856,0.1230,1.5525,-0.0078,...,0.00570,111.00850,0.49830,0.01590,0.00410,3.19270,-0.0012,0.0252,0.0081,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1532,3079.17,2405.56,2217.3777,1425.1041,1.7585,100.0,106.2556,0.1200,1.4794,-0.0198,...,0.00240,31.37710,0.50800,0.01390,0.00390,2.73280,0.0234,0.0073,0.0024,31.3771
1533,2911.37,2541.21,2207.8111,1202.4520,1.6219,100.0,108.7689,0.1212,1.5322,0.0205,...,0.00504,81.11954,0.50272,0.01556,0.00372,3.09296,0.0234,0.0073,0.0024,31.3771
1534,3085.57,2364.78,2178.6889,1657.3518,1.6603,100.0,100.8022,0.1229,1.4945,0.0247,...,0.00440,109.59960,0.49860,0.01470,0.00380,2.94930,0.0142,0.0156,0.0044,109.5996
1535,3053.49,2457.08,2172.5333,1351.9648,1.6377,100.0,103.8800,0.1243,1.5680,0.0009,...,0.00696,124.95404,0.49810,0.01320,0.00350,2.64910,0.0142,0.0156,0.0044,109.5996
1536,3120.68,2396.40,2177.0222,1448.8499,1.5565,100.0,103.2567,0.1232,1.4920,-0.0095,...,0.00534,70.91918,0.49750,0.01400,0.00360,2.80980,0.0142,0.0156,0.0044,109.5996

In [40]:
df2=preprocess.zerovarcol(features)

In [42]:
df2.head()

,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-7,Sensor-8,Sensor-9,Sensor-10,Sensor-11,...,Sensor-581,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590
0,3076.81,2158.75,2208.2334,1517.0152,1.0980,110.1900,0.1247,1.4357,0.0089,0.0052,...,0.00900,64.24050,0.5016,0.0152,0.0040,3.0319,0.0465,0.0299,0.0090,64.2405
1,2951.62,2511.92,2253.5111,1397.5060,0.9660,109.7611,0.1210,1.5527,0.0119,-0.0082,...,0.00810,0.00000,0.4953,0.0105,0.0037,2.1266,-0.0012,0.0252,0.0081,0.0000
2,2930.42,2505.17,2235.0556,1302.6607,1.6347,109.9856,0.1230,1.4588,-0.0143,0.0017,...,0.00680,73.02178,0.4958,0.0111,0.0033,2.2296,-0.0012,0.0252,0.0081,0.0000
3,2997.28,2357.99,2141.0667,1236.5212,0.9698,98.3344,0.1238,1.5973,-0.0534,-0.0284,...,0.00412,90.40428,0.4962,0.0086,0.0024,1.7297,-0.0012,0.0252,0.0081,0.0000
4,3025.10,2475.18,2235.0556,1302.6607,1.6347,109.9856,0.1230,1.5525,-0.0078,-0.0005,...,0.00570,111.00850,0.4983,0.0159,0.0041,3.1927,-0.0012,0.0252,0.0081,0.0000

116